#!/bin/bash -eu

packages=(
    automake
    bison
    build-essential
    bzip2
    ca-certificates
    curl
    flex
    g++-multilib
    gawk
    gcc-multilib
    git
    gperf
    help2man
    libglib2.0-dev
    libncurses-dev
    libtool-bin
    make
    patch
    python
    sudo
    texinfo
    wget
)

install_deps() {
  apt-get update
  export DEBIAN_FRONTEND=noninteractive
  apt-get install -y --no-install-recommends "${packages[@]}"
  rm -rf /var/lib/apt/lists/*
}

# gcc-4.8 can't be built with the make-4 that's ships with Ubuntu 15.10. This overrides it with
# make-3
mk_make() {
  local version=3.81

  curl ftp://ftp.gnu.org/gnu/make/make-${version}.tar.gz | tar xz
  pushd make-${version}
  ./configure --prefix=/usr
  make
  make install
  popd
  rm -rf make-${version}
}

mk_crosstool_ng() {
  git clone https://github.com/crosstool-ng/crosstool-ng.git
  pushd crosstool-ng
  ./configure --prefix=/usr/local
  make
  make install
  popd
  rm -rf crosstool-ng
}

create_user() {
  groupadd -r build
  useradd -m -r -g build build

  echo '%sudo ALL=NOPASSWD: ALL' >> /etc/sudoers
  adduser build sudo

  mkdir /x-tools
  chown build:build /x-tools
}

install_deps
mk_make
mk_crosstool_ng
create_user
