#!/bin/bash -eu

shopt -s nullglob
for f in /x-tools/*-unknown-linux-*/bin/*-unknown-linux-*
do
    g=$(basename "$f")

    if [ ! -e "/usr/bin/$g" ]
    then ln -vs "$f" "/usr/bin/$g"
    fi

    if [ ! -e "/usr/bin/${g//-unknown/}" ]
    then ln -vs "$f" "/usr/bin/${g//-unknown/}"
    fi
done

for f in /usr/bin/aarch64-linux-gnueabi-*
do
    g=$(basename "$f")
    mv -v "$f" "/usr/bin/${g//eabi/}"
done
shopt -u nullglob
